// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz2ZYxNjWy1C_WOAVi9ub5yAaxCSZk2NM',
    appId: '1:622513071205:web:07ca90c95c634af7c7928c',
    messagingSenderId: '622513071205',
    projectId: 'cole20-58166',
    authDomain: 'cole20-58166.firebaseapp.com',
    storageBucket: 'cole20-58166.firebasestorage.app',
    measurementId: 'G-08ZYT3FGGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApEGgWfodBjzy5KGZPmvanorOTRiXrew',
    appId: '1:622513071205:android:feb14849e860110fc7928c',
    messagingSenderId: '622513071205',
    projectId: 'cole20-58166',
    storageBucket: 'cole20-58166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-42bjNRccbeR6XL2CFBdZzV1zD0wjWg',
    appId: '1:622513071205:ios:59d0d393e86ceeb9c7928c',
    messagingSenderId: '622513071205',
    projectId: 'cole20-58166',
    storageBucket: 'cole20-58166.firebasestorage.app',
    iosBundleId: 'com.example.cole20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-42bjNRccbeR6XL2CFBdZzV1zD0wjWg',
    appId: '1:622513071205:ios:59d0d393e86ceeb9c7928c',
    messagingSenderId: '622513071205',
    projectId: 'cole20-58166',
    storageBucket: 'cole20-58166.firebasestorage.app',
    iosBundleId: 'com.example.cole20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz2ZYxNjWy1C_WOAVi9ub5yAaxCSZk2NM',
    appId: '1:622513071205:web:e187e627a00fe4ffc7928c',
    messagingSenderId: '622513071205',
    projectId: 'cole20-58166',
    authDomain: 'cole20-58166.firebaseapp.com',
    storageBucket: 'cole20-58166.firebasestorage.app',
    measurementId: 'G-NXH5MMMSWF',
  );
}
